import type { JSONContent } from "@tiptap/core";

export type BindingPrimitive = string | number | boolean | null;
export type BindingValue = BindingPrimitive | BindingValue[] | { [key: string]: BindingValue };
export type BindingData = Record<string, BindingValue>;

export type EditorNodeProps = {
  [key: string]: unknown;

  selectable?: boolean;
  selectionType?: string;
  entityType?: string;
  kind?: string;
  label?: string;
  name?: string;
  text?: string;
  bindingId?: string | null;
  mappedPath?: string;
  repeatable?: boolean;
  sampleItemsCount?: number;
  presetType?: string;
  presetId?: string;
  presetKind?: string;
  token?: string;
  description?: string;
  sourceType?: string;
  variableType?: string;
  fallback?: string;
  src?: string;
  svg?: string;
  alt?: string;
  shape?: string;
  points?: number[];
  arcType?: "open" | "pie";
  arcSweep?: 1 | -1;
  startAngle?: number;
  endAngle?: number;
  innerRadius?: number;
  outerRadius?: number;
  rows?: number;
  columns?: number;
  headerRow?: boolean;
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  opacity?: number;
  dash?: number[];
  cornerRadius?: number;
  flipX?: boolean;
  flipY?: boolean;
  richTextDisplayMode?: "label" | "technical" | "value";
  richTextJson?: JSONContent | null;
  html?: string;
  imageEditing?: Record<string, unknown> | null;
  padding?: number;
  paddingTop?: number;
  paddingRight?: number;
  paddingBottom?: number;
  paddingLeft?: number;
  textAlign?: "left" | "center" | "right";
  fontFamily?: string;
  fontSize?: number;
  fontWeight?: number | string;
  fontStyle?: string;
  letterSpacing?: number;
  lineHeight?: number;
  color?: string;
  parentId?: string;
  groupId?: string;
  grouped?: boolean;
  frameId?: string;
  containerId?: string;
  sectionId?: string;
  layerId?: string;
  layerName?: string;
  layerOrder?: number;
  layerVisible?: boolean;
  layerLocked?: boolean;
  visible?: boolean;
  locked?: boolean;
};
