export type BindingPrimitive = string | number | boolean | null;

export interface BindingData {
  [key: string]: BindingValue;
}

export type BindingValue = BindingPrimitive | BindingValue[] | BindingData;

export type EditorNodeProps = {
  selectable?: boolean;
  selectionType?: string;
  entityType?: string;
  kind?: string;
  label?: string;
  name?: string;
  title?: string;
  text?: string;
  html?: string;
  bindingId?: string | null;
  mappedPath?: string;
  repeatable?: boolean;
  sampleItemsCount?: number;
  sampleValue?: BindingValue;
  presetType?: string;
  presetId?: string;
  presetKind?: string;
  token?: string;
  description?: string;
  sourceType?: string;
  variableType?: string;
  fallback?: BindingValue;
  src?: string;
  svg?: string;
  alt?: string;
  shape?: string;
  points?: number[];
  arrow?: boolean;
  arcType?: "open" | "pie";
  arcSweep?: 1 | -1;
  startAngle?: number;
  endAngle?: number;
  innerRadius?: number;
  outerRadius?: number;
  rows?: number;
  columns?: number;
  headerRow?: boolean;
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  opacity?: number;
  dash?: number[];
  cornerRadius?: number;
  flipX?: boolean;
  flipY?: boolean;
  richTextDisplayMode?: "label" | "technical" | "value";
  richTextJson?: unknown;
  imageEditing?: unknown;
  padding?: number;
  paddingTop?: number;
  paddingRight?: number;
  paddingBottom?: number;
  paddingLeft?: number;
  textAlign?: "left" | "center" | "right" | "justify";
  fontFamily?: string;
  fontSize?: number;
  fontWeight?: number | string;
  fontStyle?: string;
  letterSpacing?: number;
  lineHeight?: number;
  color?: string;
  parentId?: string;
  groupId?: string;
  grouped?: boolean;
  frameId?: string;
  containerId?: string;
  sectionId?: string;
  layerId?: string;
  layerName?: string;
  layerOrder?: number;
  layerVisible?: boolean;
  layerLocked?: boolean;
  visible?: boolean;
  locked?: boolean;
  crop?: unknown;
  mask?: unknown;
  filter?: unknown;
  adjustments?: unknown;
  transform?: unknown;
  [key: string]: unknown;
};
